// Builds a repo's visual fixture into a static dir scene.ts can serve, without
// touching the repo: the vite config is a temp file under --out that imports
// the repo's own config (plugins, aliases, dedupe) and retargets only where
// the build reads from and writes to.
import { existsSync, mkdirSync, readdirSync, realpathSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";
import { parseArgs } from "node:util";
import { exitOnHelp } from "./lib/ffmpeg.ts";

const USAGE = "bun helpers/fixture-build.ts --repo <path> --fixture <name> --out <dir> [--json]";
const DESCRIPTION = `
Builds <repo>/tools/visual/<name>-fixture.html with the repo's own vite and
vite.config.ts into <out>/dist, leaving the repo untouched: the generated config
and vite cache live under --out, which must be outside the repo. Install the
repo's dependencies first.
Prints the built entry; with --json, {root, entry, config, wallSeconds}, where
root and entry drop straight into scene.json.
Exit 0 on a finished build; 2 on usage or build errors.
`;

class UsageError extends Error {}

function inside(child: string, parent: string): boolean {
  return child === parent || child.startsWith(parent + sep);
}

function main() {
  const started = Date.now();
  const { values } = parseArgs({
    args: Bun.argv.slice(2),
    options: { repo: { type: "string" }, fixture: { type: "string" }, out: { type: "string" }, json: { type: "boolean" } },
    strict: true,
  });
  if (!values.repo || !values.fixture || !values.out) throw new UsageError("need --repo, --fixture and --out");
  const repo = resolve(values.repo);
  const repoConfig = join(repo, "vite.config.ts");
  const vite = join(repo, "node_modules", ".bin", "vite");
  const input = join(repo, "tools", "visual", `${values.fixture}-fixture.html`);
  if (!existsSync(repoConfig)) throw new UsageError(`no vite.config.ts in ${repo}`);
  if (!existsSync(vite)) throw new UsageError(`no ${vite}; install the repo's dependencies first`);
  if (!existsSync(input)) throw new UsageError(`no fixture html: ${input}`);
  const out = resolve(values.out);
  // The case-insensitive FS makes a plain prefix check unreliable; compare realpaths too.
  if (inside(out, repo) || inside(out.toLowerCase(), realpathSync(repo).toLowerCase())) {
    throw new UsageError(`--out must be outside the repo: ${out}`);
  }

  const dist = join(out, "dist");
  const config = join(out, "vite.config.product-video.mts");
  mkdirSync(out, { recursive: true });
  writeFileSync(
    config,
    `// Generated by product-video fixture-build. Not part of ${repo}.
import repoConfig from ${JSON.stringify(repoConfig)};
const env = { command: "build", mode: "production", isSsrBuild: false, isPreview: false };
const base = await (typeof repoConfig === "function" ? repoConfig(env) : repoConfig);
export default {
  ...base,
  root: ${JSON.stringify(repo)},
  base: "/",
  cacheDir: ${JSON.stringify(join(out, ".vite-cache"))},
  build: {
    ...base.build,
    outDir: ${JSON.stringify(dist)},
    emptyOutDir: true,
    rollupOptions: { ...base.build?.rollupOptions, input: ${JSON.stringify(input)} },
  },
};
`,
  );

  const r = Bun.spawnSync([vite, "build", "--config", config, "--logLevel", "warn"], {
    cwd: repo,
    stdout: "pipe",
    stderr: "pipe",
  });
  if (r.exitCode !== 0) {
    const tail = (r.stderr.toString() + r.stdout.toString()).trim().split("\n").slice(-8).join("\n");
    throw new UsageError(`vite build failed (${r.exitCode}):\n${tail}`);
  }

  // With root = repo the entry lands at tools/visual/; lift it to the dist root
  // so a scene names it plainly. Assets are absolute under base "/", so it still loads.
  const entry = `${values.fixture}-fixture.html`;
  const built = join(dist, "tools", "visual", entry);
  if (!existsSync(built)) throw new UsageError(`vite did not emit ${built}`);
  renameSync(built, join(dist, entry));
  for (const d of [join(dist, "tools", "visual"), join(dist, "tools")]) {
    if (existsSync(d) && readdirSync(d).length === 0) rmSync(d, { recursive: true });
  }

  const report = { root: dist, entry, config, wallSeconds: (Date.now() - started) / 1000 };
  console.log(values.json ? JSON.stringify(report) : `built ${join(dist, entry)} in ${report.wallSeconds}s`);
}

exitOnHelp(USAGE, DESCRIPTION);
try {
  main();
  process.exit(0);
} catch (e) {
  const known = e instanceof UsageError || (e as { code?: string })?.code?.startsWith("ERR_PARSE_ARGS");
  console.error(known ? (e as Error).message : (e as Error)?.stack ?? String(e));
  console.error(`usage: ${USAGE}`);
  process.exit(2);
}
